apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hlf-operator.fullname" . }}-leader-election-role

rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - tcproutes
      - tlsroutes
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hlf-operator.fullname" . }}-manager-role
rules:
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - replicasets
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - pods/log
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - pods/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - ingresses
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - configmaps
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - pods
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - pods/log
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - pods/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - ingresses
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - secrets
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - services
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - apps
    resources:
      - ingresses
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - configmaps
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - deployments
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - persistentvolumeclaims
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - pods
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - pods/log
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - pods/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - secrets
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - extensions
    resources:
      - services
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperationsconsoles
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperationsconsoles/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperationsconsoles/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperatorapis
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperatorapis/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperatorapis/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperatoruis
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperatoruis/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricoperatoruis/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricpeers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricpeers/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricpeers/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricorderernodes
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricorderernodes/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricorderernodes/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricorderingservices
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricorderingservices/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricorderingservices/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabriccas
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabriccas/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabriccas/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricnetworkconfigs
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricnetworkconfigs/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricnetworkconfigs/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricchaincodes
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricchaincodes/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricchaincodes/status
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricfollowerchannels
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricfollowerchannels/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricfollowerchannels/status

  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricmainchannels
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricmainchannels/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricmainchannels/status


  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricidentities
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricidentities/finalizers
  - verbs:
      - get
      - patch
      - update
    apiGroups:
      - hlf.pkuidlabs.com
    resources:
      - fabricidentities/status


  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.istio.io
    resources:
      - gateways
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
     - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - monitoring.coreos.com
    resources:
      - podmonitors
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
  - verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - get
      - update
      - patch
    apiGroups:
      - ''
    resources:
      - configmaps/status
  - verbs:
      - create
      - patch
    apiGroups:
      - ''
    resources:
      - events
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses
      - gateways
      - httproutes
      - tcproutes
      - tlsroutes
    verbs:
      - get
      - list
      - watch
      - create
      - patch
  - apiGroups:
      - gateway.networking.k8s.io
    resources:
      - gatewayclasses/status
      - gateways/status
      - httproutes/status
      - tcproutes/status
      - tlsroutes/status
    verbs:
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hlf-operator.fullname" . }}-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hlf-operator.fullname" . }}-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hlf-operator.fullname" . }}-leader-election-rolebinding

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hlf-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hlf-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hlf-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Release.Namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hlf-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "hlf-operator.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{.Release.Namespace}}

